- name: "Check for groups existence"
  shell: getent group {{ sudo_group }}
  register: group
  when: sudo_group is defined
  ignore_errors: true

- name: "Create sudoers file for sudo_group in /etc/sudoers.d"
  ansible.builtin.template:
    src: group.j2
    dest: '/etc/sudoers.d/{{ sudo_group | regex_replace("[^A-Za-z0-9]", "") }}'
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  when:
    #- ssh_group is defined
    - group.rc == 0
